### ISSUE TITLE
Add support for pebbleDB

### ISSUE THREAD

**Issue by GAtom22** [cometbft/cometbft-db#90]
PebbleDB is not supported.

Would be great to have this included in this repo to avoid having to replace this dependency with a fork (e.g.[ notional's](https://github.com/notional-labs/cometbft-db/tree/pebble)) that includes pebbleDB when required by node operators.

**Comment by melekes** [comment]
We're considering dropping support for multiple databases in favor of a single optimized database - https://github.com/cometbft/cometbft/issues/48. Would you be willing to add `PebbleDB` and provide benchmarks to see how it compares to other databases?

**Comment by faddat** [comment]
I will.  It destroys all others in terms of performance.  

Just, erm:

* https://github.com/tendermint/tm-db/pulls?q=is%3Apr+is%3Aclosed+pebble

Lotta resistence there historically

**Comment by faddat** [comment]
Hey guys, I think that in the end it's best at notional just license a happier comet and I think apache lets us do that. 

If anybody wants it for their chain we're a very open to governance licensing

**Comment by melekes** [comment]
> @melekes - would you want it like this?

I'm in favor of adding `pebble`. We should also do some experiments similar to https://github.com/ethereum/go-ethereum/pull/24615 before making a choice wrt https://github.com/cometbft/cometbft/issues/1039.

**Comment by adizere** [comment]
Would be glad to add support for PebbleDB (and even deprecate all others per https://github.com/cometbft/cometbft/issues/48). To do so, we need clear user signals so that we don'r rug anyone and force them to use Pebble when they want to use something else.

Let's also discuss this at the next community call (this Thursday). Would be great if you can join @faddat !
